### PR TITLE
abi/gen: generate Item wrappers from abi json

### PR DESCRIPTION
**Pull request by ryandotsmith**
This branch has diverged. I will break it up into more atomic commits.

### CODE REVIEW

**Comment by lechengfan** [comment]
Will this be able to handle static length arrays? Like if the type was `address[4]`

**Comment by ryandotsmith** [comment]
> Will this be able to handle static length arrays? Like if the type was `address[4]`

Not as it stands, need to do that before merging. Good call.

**Comment by ryandotsmith** [comment]
@lechengfan last commit adds support for fixed size arrays. wow. it came together really easily. i'm liking this code!

**Review by lechengfan — APPROVED** [review]

**Comment by lechengfan** [comment]
Nice! this looks awesome to use

**Comment by ryandotsmith** [comment]
I had a fundamental misunderstanding of how ABI encoding worked. I had incorrectly assumed that a list of tuples would roughly encode to:

```
0: list at 1
1: list size 2
2: tuple at 4
3: tuple at 6
4: static tuple field 1
5. static tuple field 2
6. static tuple field 1
7. static tuple field 2
```
when in fact it is:
```
0: list at 1
1: list size 2
2: static tuple field 1
3. static tuple field 2
4. static tuple field 1
5. static tuple field 2
```

The last commit d5de796 fixes the bug.

At this point, the commit is to wild to simply land. I will begin cleaning up and creating atomic pull requests.

**Comment by ryandotsmith** [comment]
I am feeling very good about the state of the ABI code at this point. I have corrected my fundamental misunderstanding about the distinction between static and dynamic types and consequently the code is much tighter now. I have tested this extensively on real world contracts with tuple arrays and things work swimmingly! What a journey. I'm going to celebrate with a root beer.

--ps
There was a section in the ABI spec that I didn't pay close enough attention to and my lake of awareness caused much pain. Here is the section:

```
Definition: The following types are called “dynamic”:

bytes
string
T[] for any T
T[k] for any dynamic T and any k >= 0
(T1,...,Tk) if Ti is dynamic for some 1 <= i <= k

All other types are called “static”.
```

**Comment by ryandotsmith** [comment]
The ABI encoding bugs have been added to main in #63 and #64

Next I will add the code gen bits in a new PR.

**Comment by ryandotsmith** [comment]
closing in favor of #68

**Pull request closed without merging**
