### PR TITLE
ai generated readme

### PR DESCRIPTION
**Pull request by shawnharmsen**
used https://github.com/eli64s/readme-ai#-using-readme-ai with gpt4 to make a readme
- Icons probably need to be changed
- some of the stuff could probably be cut

### CODE REVIEW

**Comment by ryandotsmith** [comment]
Thanks for taking the time to do this! I don't think I'll merge it though as it doesn't fit my style.

That being said, I am open to suggestions for how to make the readme more useful. Is there something in particular that you think is missing from the current readme? Obviously it's very bare at this point, what's the first thing you would add to it?

**Comment by shawnharmsen** [comment]
yeah I agree this is too clunky 

mostly
1. confused whether I need to run geth or not
2. how do I run this
3. estimated size for running
- geth for each chain
- optimism
- base
- mainnet

4. I've been spamming you on Twitter with my sproto persona haha and looking to contribute with actual code

I'll open a new PR later

**Comment by ryandotsmith** [comment]
Your comments make perfect sense. There isn't a great document that answers all those questions and there should be!

Part of the issue is that I'm just now beginning to see a vision for how E2PG and RLPS play together. Consequently I'm thinking about rebranding the product offering. I'd like to combine the concept of RLPS and E2PG to mean:

> A single daemon that you run alongside your app and postgres database that downloads data from multiple chains via Index Supply's hosted nodes, indexes specific contracts and flows, and writes the indexed data to your postgres database.

> The daemon is free and open source. The indexed data lives in your PG database. The blockchain data is delivered via an open protocol powered by Index Supply's hosted nodes and is can be accessed for a monthly fee. Fee tiers are as follows: $30, $300, and $3,000

**Comment by shawnharmsen** [comment]
awesome ser yeah I will definitely sign up

**Pull request closed without merging**
